### ISSUE TITLE
Need WaterFall type chart 

### ISSUE THREAD

**Issue by pooja-sanjay-joshi** [AnyChart/AnyChart-Qlik#1]
Hi Team,

It will be of great help if you can provde WaterFall chart.

**Comment by loki20beta** [comment]
@pooja-sanjay-joshi it is in our [roadmap](http://www.anychart.com/products/anychart/roadmap/), we will do our best to release it in a couple of months

**Comment by RomanLubushkin** [comment]
@pooja-sanjay-joshi Glad to inform you that Waterfall Chart type is assigned to [release v2.1.0](https://github.com/AnyChart/AnyChart-Qlik#version-21---nov-2017) and will be added on Dec 2017

**Comment by RomanLubushkin** [comment]
@pooja-sanjay-joshi , glad to inform you that we have added Waterfall Chart in the [release v2.1.0|https://github.com/AnyChart/AnyChart-Qlik/releases/tag/v2.1.0]
