### ISSUE TITLE
Legend&Tooltip Appearing Inaccurate Series Name

### ISSUE THREAD

**Issue by lincssamuel** [AnyChart/AnyChart-Qlik#12]
Hi, 

Screenshot probably works the best to describe the issue. The chart updates based on the variable selected, the values, area are correct, but the legend and the tooltip are showing incorrect names:

this is the correct version (by default TV is selected) and you can see that the tooltip and the legend mention "TV"

![image](https://user-images.githubusercontent.com/7426502/41519979-276c3348-7280-11e8-827e-7d7120923b7a.png)

However, if I select Affiliates:
only the first legend and tooltip item updated to affiliates and the rest still is TV

![image](https://user-images.githubusercontent.com/7426502/41520051-81b991ce-7280-11e8-9b08-a608de37b21a.png)

however, with "Affiliates" selected, if I run chart editor, it's appearing correctly. 

![image](https://user-images.githubusercontent.com/7426502/41520071-b52ce790-7280-11e8-967e-a9157925cef9.png)

You can see that my screenshot are showing the charts in a container extension, the same happens if I use the anyChart itself.

In case if you are interested, one of the measurement label is:

='Retained-Non' &
if(vMsource1=1, 'TV', if(vMsource1=2, 'Affiliates', if(vMsource1=3, 'Paid Search', if(vMsource1=4, 'Email', if(vMsource1=5, 'Direct', 
if(vMsource1=6, 'Organic Search', if(vMsource1=7, 'Paid Social', if(vMsource1=8, 'Display', if(vMsource1=9, 'Customer Service', if(vMsource1=10, 'Direct Mail'
))))))))))

Thank you and please let me know if you think I am doing something wrong or this could be a bug. 

AnyChart is an awesome extension!!
Samuel

**Comment by Shestac92** [comment]
@lincssamuel 
Do you switch series with a control on the left side from the chart? (marked with a red circle on your screenshot below)
Is it a Qlik built-in control or any other third-party plugin?
We'd like to learn more about this functionality to reproduce it.

**Comment by lincssamuel** [comment]
@Shestac92 

Let me try to explain, 

In Qlik script load, I have this line:

SET vMsource1=1;

and in the front end, I use an extension called "Variable" http://branch.qlik.com/#!/project/56728f52d1e497241ae697f8

basically "Varhe iable" is just a way to assign different value to the variable in the front end. 

so when I select on TV, vMsource is 1, and when I select Affiliates, vMsource is 2, etc. 

for measurement expression, an example is:

Count(distinct {<L12MRevenue={">0"},
MarketingSource_Category1={"$(=Pick(Match($(vMsource1),1,2,3,4,5,6,7,8,9,10),
'TV', 'Affiliates', 'Paid Search', 'Email', 'Direct', 'Organic Search', 'Paid Social', 'Display', 'CustomerService', 'Direct Mail'
))"}>}MasterContactID)/1000

basically using the variable in set analysis, this portion is working correctly in AnyChart. 

and its "Label"
![image](https://user-images.githubusercontent.com/7426502/41547575-6aeb6ca6-72d5-11e8-8a9a-ea7c21a188fe.png)

='Retained-' &
if(vMsource1=1, 'TV', if(vMsource1=2, 'Affiliates', if(vMsource1=3, 'Paid Search', if(vMsource1=4, 'Email', if(vMsource1=5, 'Direct', 
if(vMsource1=6, 'Organic Search', if(vMsource1=7, 'Paid Social', if(vMsource1=8, 'Display', if(vMsource1=9, 'Customer Service', if(vMsource1=10, 'Direct Mail'
))))))))))

which controls what to appear for tooltip and the legend, as I mentioned in the first comment, when I run edit chart works fine, but the chart's tooltip and legend doesn't update correctly when I am selecting the variables on the front end (the areas and lines are working correctly)

Please let me know if you have any questions with any of the above

Thank you,

**Comment by Shestac92** [comment]
@lincssamuel 
Thank you for this clarification and your report!
We will reproduce and investigate this issue. We will update you as we get any results.

**Comment by Shestac92** [comment]
@lincssamuel 
We tried to reproduce the same issue, but we didn't succeed with getting vMsource1 value from the "Variable" extension. Can you share with us a sample of how do you get that value? The rest is ready to go.

**Comment by lincssamuel** [comment]
@Shestac92 

Hi Alex,

https://drive.google.com/open?id=15hlkYUdzlDW0OTeYcC5HM_oxX7igTaXN is a .qvf with partial data load. Please let me know if this could be a sample for you. 

Thank you,

**Comment by Shestac92** [comment]
@lincssamuel 
thank you for the sample! We will look into it.

**Comment by Shestac92** [comment]
@lincssamuel 
We glad to inform you that the fix is available. Please, download the latest version of AnyChart Qlik plugin 2.4.1 to get the update. 
Also, we wish to call your attention to the fact that you should update the Chart Editor, then open your Qlik application, open Chart Editor and click 'Complete' to make the application work properly.
Thank you for your report!
