### ISSUE TITLE
Date dimension format problem

### ISSUE THREAD

**Issue by ZiaboBaz** [AnyChart/AnyChart-Qlik#2]
All dates are currently shown as 5 digit numbers. 
{%Date}{"%yy-%M-%d"} does not solve the issue

**Comment by RomanLubushkin** [comment]
@ZiaboBaz , thank you for your report, glad to inform you that in new AnyChart Qlik Extension 2.0 you can use [String Tokens|https://docs.anychart.com/Common_Settings/Text_Formatters#string_tokens] to format any kind of text of the AnyChart charts. For example, the format you have mentioned can be done as follows:
```
{%Value}{dateTimeFormat:yy-MM-d}
```
