### ISSUE TITLE
Qlik Sense June and September

### ISSUE THREAD

**Issue by felipedse** [AnyChart/AnyChart-Qlik#20]
Hi, I noticed that the extension is not working when the server is updated to the last Qlik Sense version.
Does anybody else faced the same problem?

Thanks in advance,

**Comment by Shestac92** [comment]
@felipedse 
Do you use the free Qlik Sense desktop version or paid cloud server version?

**Comment by felipedse** [comment]
Enterprise Server

**Comment by alejobs** [comment]
Hi,
I am also experiencing the same problem. The error I get is:

`Error: layout.anychart is undefined`

**Comment by PlexPro** [comment]
I just installed this in Enterprise, Qlik Sense June 2018 (12.26.1).  I have recycled the services to ensure functionality.  When I drop the extension onto a sheet open for edit, I get a message that the extension cannot be found on the server:

Invalid visualization
The visualization was not found on the server: anychart-qlik
[Delete]

The only thing that I can do is to delete it.

We do make use of a "QlikShare" for backup purposes (pursuant the recommendations of Level 1 support), at '\\VM-WIN-ANALYTIC\QlikShare", defined as the Root Folder of the Service Cluster.  Thus the extension does not exist at the standard location.  Could that be the cause?

René V.

**Comment by Shestac92** [comment]
@PlexPro 
Usually, all extensions should be placed in the special directory according to [this article](https://help.qlik.com/en-US/sense/September2018/Subsystems/ManagementConsole/Content/Sense_QMC/import-extensions.htm).
Probably the custom path is available, but we don't have this information. Only the Qlik support team can confirm that.

**Comment by PlexPro** [comment]
Hi,

>> ...all extensions should be placed in the special directory according to this article.

It is located normally, according to that article.

According to the system log "VM-WIN-ANALYTIC_System_Repository.txt", the file "anychart-editor.min.css" cannot be found; I will download the new version and hope that fixes it.

**Comment by Shestac92** [comment]
@PlexPro @alejobs @felipedse 
We are glad to notify you that the last versions of Qlik Sense Enterprise November 2018 (12.44.1 and higher) works perfectly with the last version of AnyChart Qlik Extension.
Please, firstly, download the latest version of AnyChart Qlik Extension. This includes many fixes and improvements.

**Comment by Marshall-JamesRaynor** [comment]
i have download the last version of anychart but with qliksense june doesn't work.

you know why?

**Comment by loki20beta** [comment]
@Marshall-JamesRaynor qlik desktop or qlik server? which version?

**Comment by Marshall-JamesRaynor** [comment]
server  June 2018

**Comment by loki20beta** [comment]
@Marshall-JamesRaynor can you upgrade qlik to  November 2018 (12.44.1 and higher) qlik version?

**Comment by Marshall-JamesRaynor** [comment]
@loki20beta  no i can't because our costumer don't want

**Comment by Marshall-JamesRaynor** [comment]
I understood what the problem was. another extension had a bug and also sent the anychart into error. I confirm that the latest version works with the version of June.thank you for your help
