### ISSUE TITLE
problem with date order

### ISSUE THREAD

**Issue by whruiqlik** [AnyChart/AnyChart-Qlik#21]
How to solve this problem? 

![anychart](https://user-images.githubusercontent.com/43289168/47265510-7ebf3300-d55b-11e8-81f1-f2b5189956c0.png)

**Comment by Shestac92** [comment]
@whruiqlik 
This behavior can occur if the xScale is the ordinal type. Do you use the default ordinal xScale or dateTime scale?
If you are not sure, please, provide us with the chart configuration code and we will review it.

**Comment by whruiqlik** [comment]
The problem has been solved. AnyChart no problem. It's data. Thanks！
