### ISSUE TITLE
How can we get Multi Dimension line charts?

### ISSUE THREAD

**Issue by joychugh** [AnyChart/AnyChart-Qlik#25]
I wanted to have a line chart with 2 dimensions
1) Date (the X axis)
2) DimensionX - (the name of the series that I am comparing)

Is that not supported?

**Comment by Shestac92** [comment]
@joychugh 
We are going to add to add categorizedBySeries feature in the upcoming update of AnyChart Qlik extension (January 2019). Using this feature you will be able to create the second option `DimensionX - (the name of the series that I am comparing)`.
Unfortunately, this option impacts on all chart series. I mean that you can't render both options on the same chart. You should create one line chart with Date (the X axis) and the second chart with DimensionX. 
In plain JS the second option looks [like this](https://playground.anychart.com/maBf32jQ).

**Comment by Shestac92** [comment]
@joychugh 
we are glad to notify you that we have released the new version of AnyChart Qlik Extension!
The new extension was totally reworked, it brings many new features, improvements and bug fixes.
Also, the new version includes improvements you requested.
Thank you for your suggestions!

The new version is available [here](https://www.anychart.com/technical-integrations/samples/qlik-charts/download/) 
The new installation guide you can check [here](https://www.anychart.com/technical-integrations/samples/qlik-charts/docs/)
