### ISSUE TITLE
AnyChart 8.5

### ISSUE THREAD

**Issue by lucandmendes** [AnyChart/AnyChart-Qlik#26]
Hi Anychart 8.5 was realeased, with a new feature wich is good for multi linear charts...
There's a way to implement 8.5 anychart just released to this qlik "old" extension version? Or how long to a new Any Chart Qlik Sense extension release?
Thank you!

**Comment by Shestac92** [comment]
@lucandmendes 
AnyChart Qlik extension always updates soon after the AnyChart JS library releases. Very soon we are going to update the extension including 8.5.0 version of the library. But the extension is still at the development stage and we add new features in every update. Please, can you specify which new features (from 8.5.0) would you like to get in the next extension update?
