### ISSUE TITLE
How to convert data into K units?

### ISSUE THREAD

**Issue by whruiqlik** [AnyChart/AnyChart-Qlik#27]
How to convert data into K units?  Keep thousand bit separator at the same time.
For example, 10,000,000 --> 10,000K
Thanks!

**Comment by Shestac92** [comment]
@whruiqlik 
To achieve that you can use string tokens and formatting parameters. 
For your purpose, you can use the following string token:
`{%Value}{scale:(1000))|( k),groupsSeparator:\,}`.
You can use it in any setting which supports string tokens (all labels, tooltip's content etc).
Below you can find an example of a similar token for Y-axis labels (I used 100 instead 1000 just for demonstration purposes).
![tokens](https://user-images.githubusercontent.com/24609062/51094419-abe05200-17e7-11e9-9129-8a22a186272a.png)

[This article](https://docs.anychart.com/Common_Settings/Text_Formatters#formatting_parameters_list) describes how to use string tokens and special parameters.
