### ISSUE TITLE
Not able to change date/number formats in pop-up window

### ISSUE THREAD

**Issue by ZiaboBaz** [AnyChart/AnyChart-Qlik#3]
while pointing on the chart, the pop-up windows appears. the format of the numbers inside the pop-up is not affected by format set in labels sections of the X and Y axis properties.

**Comment by RomanLubushkin** [comment]
@ZiaboBaz , thank you for your report.
I guess you're talking about data points tooltips, glad to inform you that we have released AnyChart Qlik Extension v2.0 which provides an ability to fully setup tooltips settings including text format for tooltip title and each series.
