### ISSUE TITLE
How to display an average line in anychart?

### ISSUE THREAD

**Issue by whruiqlik** [AnyChart/AnyChart-Qlik#34]
How to display an average line in anychart? Thank you!

![20200707120146](https://user-images.githubusercontent.com/43289168/86707065-24754700-c04a-11ea-8e24-98f1ae136252.png)

**Comment by Shestac92** [comment]
@whruiqlik 
You can achieve that by creating the second line series from a measure with the specific function expression.
Step1: Add the second measure with the fx `Avg(TOTAL Aggr(value1, [Month]))`
Where `value1` is a measure for the first (main) series and `Month` is a dimension.
<img width="385" alt="sample1" src="https://user-images.githubusercontent.com/24609062/86750814-cd369d00-c070-11ea-9666-6ca76099c38b.png">

Step2: Create and configure a series from the second measure. Below are the resulting chart and the table that represents calculated values.
<img width="1168" alt="sample2" src="https://user-images.githubusercontent.com/24609062/86751282-2272ae80-c071-11ea-8b0e-166db9ea88c2.png">

**Comment by whruiqlik** [comment]
It's OK. Thank you very much!
