### ISSUE TITLE
How to make a year-on-year chart

### ISSUE THREAD

**Issue by whruiqlik** [AnyChart/AnyChart-Qlik#35]
How to use anychart to do the same as the chart in the following picture: X axis is month, line is year, thank you!

![20200708155301](https://user-images.githubusercontent.com/43289168/86893860-d721d400-c134-11ea-95d1-793531581b82.png)

**Comment by Shestac92** [comment]
@whruiqlik 
To achieve that you need one Dimension `Month` and three measures by years. The data table should look like below:
<img width="846" alt="sample1" src="https://user-images.githubusercontent.com/24609062/87019019-ad37e280-c204-11ea-9eff-9f9070d03f67.png">

The dimensions and measures configuration:
<img width="999" alt="sample2" src="https://user-images.githubusercontent.com/24609062/87019045-b5901d80-c204-11ea-9c84-33cd50ed2c17.png">

Then make sure that the extensions mapped series correctly. If it doesn't then simply apply a correct field to every series in the Data tab of the Chart Editor.
<img width="1331" alt="sample3" src="https://user-images.githubusercontent.com/24609062/87019171-dce6ea80-c204-11ea-8b42-145b07228af3.png">

After applying some visual settings it will look the same:
<img width="1028" alt="sample4" src="https://user-images.githubusercontent.com/24609062/87019442-33ecbf80-c205-11ea-99cb-e1f9a74b4567.png">

**Comment by whruiqlik** [comment]
Thank you very much!
