### ISSUE TITLE
Add measures to anychart

### ISSUE THREAD

**Issue by escarber** [AnyChart/AnyChart-Qlik#5]
Hello,  
I would like to add 2 more measures to this anychart.  I was able to add 2 more measures to the properties.js.  Now I need to figure out had to add the 2 more measures to the visual chart.  Can you assist me.

**Comment by loki20beta** [comment]
@escarber we are working on the update of the component that will add multiple measures support.

**Comment by escarber** [comment]
Thank you very much for your help on this.  Do you have an ETA on when this would be done?

Ed Scarberry
Analyst Applications Development
AES | U.S. SBU | IPL
317-261-5043-- Office
317-474-2178—Cell
Ed.scarberry@aes.com<mailto:Ed.scarberry@aes.com>
[aes]  [ipl]

**Comment by loki20beta** [comment]
@escarber we will do out best to provide an ETA this week.

**Comment by escarber** [comment]
Hope all is well.  Do you have an ETA on this so I can plan this with my business users?

Ed Scarberry
Analyst Applications Development
AES | U.S. SBU | IPL
317-261-5043-- Office
317-474-2178—Cell
Ed.scarberry@aes.com<mailto:Ed.scarberry@aes.com>
[aes]  [ipl]

**Comment by loki20beta** [comment]
@escarber we will most likely roll it out next week

**Comment by escarber** [comment]
Thank you very much.

Ed Scarberry
Analyst Applications Development
AES | U.S. SBU | IPL
317-261-5043-- Office
317-474-2178—Cell
Ed.scarberry@aes.com<mailto:Ed.scarberry@aes.com>
[aes]  [ipl]

**Comment by escarber** [comment]
Hello hope all is well.  I am wondering if the changes have been  completed.

**Comment by escarber** [comment]
Hello,
  I am checking in to see if that measure fix has been done.  I did notice a new version of anychart on branch.qlik.com.  I did see you can add more than 6 measures.  But when I go to run chart editor the Date Set 1 only shows 6 measures.  Not sure if I missed a step or this version is not the fix I requested.

**Comment by escarber** [comment]
Hello,
  I am checking in to see if that measure fix has been done. We would like to use this soon.   I did notice a new version of anychart on branch.qlik.com.  I did see you can add more than 6 measures.  But when I go to run chart editor the Date Set 1 only shows 6 measures.  Not sure if I missed a step or this version is not the fix I requested.

**Comment by RomanLubushkin** [comment]
This issue duplicates [Need to add more measures in the Chart Editor](https://github.com/AnyChart/AnyChart-Qlik/issues/6) so I'm closing this one.
