### ISSUE TITLE
Need to add more measures in the Chart Editor.

### ISSUE THREAD

**Issue by escarber** [AnyChart/AnyChart-Qlik#6]
I did notice a new version of anychart on branch.qlik.com.  I did see you can add more than 6 measures now.  But when I go to run chart editor the Data Set 1 only shows 6 measures.  Not sure if I missed a step or this version is not the fix I requested.  I have 8 measures but cannot add all 8 to the Chart.

**Comment by RomanLubushkin** [comment]
@escarber , thank you for your report, we confirm this problem and going to fix it ASAP. You can expect an update on Monday or even earlier.

**Comment by RomanLubushkin** [comment]
@escarber glad to inform you that we have fixed issues with measures count in [v2.1.0|https://github.com/AnyChart/AnyChart-Qlik/releases/tag/v2.1.0], it would be nice if you try v2.1.0 and confirm that all problems are solved

**Comment by escarber** [comment]
That seems to have fixed it.  Thank you so much
