### ISSUE TITLE
Possibility changing line stroke thickness

### ISSUE THREAD

**Issue by Victabv** [AnyChart/AnyChart-Qlik#7]
Hello!

thank you for the great extension. Was wondering if it is possible to change the thickness value of an line-chart. Would like to use it as a combo chart and change the thickness of the lines.

Kind regards,

Victa

**Comment by maresha** [comment]
Victa,

thank you for the feedback! 

Sure, you can control line visual settings with stroke() method:
https://api.anychart.com/8.0.1/anychart.core.StateSettings#stroke
I made the simple sample with two line series to illustrate the possibilities: https://jsfiddle.net/gsoo0a0u/
Please check it and let me know if it won't suit your needs.

Also, as far as you are going to build combined charts, some additional information about z-index feature might be helpful too. AnyChart allows defining different z-index for different series, like here: https://jsfiddle.net/dymum0vj/

**Comment by RomanLubushkin** [comment]
@Victabv 
Sure, you can use control highlighted on the screenshot
![image](https://user-images.githubusercontent.com/680750/34704615-46541a50-f535-11e7-9d18-9c95a5ab9ae5.png)
